# Generated by Django 4.2 on 2023-06-03 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=50, null=True)),
                ('best_way_reach', models.CharField(blank=True, max_length=20, null=True)),
                ('best_time_reach', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_or_pay', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance', models.CharField(blank=True, max_length=20, null=True)),
                ('do_you_have_secondary_insurance', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_insurance_carrier', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_insurance', models.CharField(blank=True, max_length=20, null=True)),
                ('current_psychiatric_diagnosis', models.CharField(blank=True, max_length=20, null=True)),
                ('current_medications', models.CharField(blank=True, max_length=20, null=True)),
                ('current_psychiatric_prescriber', models.CharField(blank=True, max_length=20, null=True)),
                ('history_of_suicide_attempts', models.TextField(blank=True, null=True)),
                ('history_of_self_injurious_behavior', models.TextField(blank=True, null=True)),
                ('history_of_eating_disorder', models.TextField(blank=True, null=True)),
                ('history_of_substance_abuse', models.TextField(blank=True, null=True)),
                ('emergency_contact_firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
