# Generated by Django 4.2 on 2023-06-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_rename_first_name_additionalinformation_firstname_and_more'),
        ('medic_app', '0002_alter_ailments_id_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='add_info',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.additionalinformation'),
        ),
    ]
