# Generated by Django 4.2 on 2023-06-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='review',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
